export const siteConfig = {
  name: "Name",
  description: "Description",
  header: [
    { name: "Home", href: "/" },
    {
      name: "Shop",
      href: "#",
      category: [
        { name: "All products", slug: "" },
        { name: "New products", slug: "new_products" },
        { name: "Best Sellers", slug: "best_sellers" },
        { name: "Chocolate cakes", slug: "chocholate_cakes" },
        { name: "Fruit cakes", slug: "fruit_cakes" },
        { name: "Coffee cakes", slug: "coffee_cakes" },
        { name: "Breakfast bars", slug: "breakfast_bars" },
        { name: "Energy bites", slug: "energy_bites" },
        { name: "Chocolate bars", slug: "chocholate_bars" },
      ],
    },
    { name: "Delivery/Pick up", href: "/delivery_pickup" },
    { name: "About us", href: "/about" },
    { name: "Contact us", href: "/contact" },
  ],
  footer: [
    { name: "Delivery/Pick up", href: "/delivery_pickup" },
    { name: "About us", href: "/about" },
    { name: "Contact us", href: "/contact" },
    {
      name: "Shop",
      href: "#",
      category: [
        { name: "All products", slug: "" },
        { name: "New products", slug: "new_products" },
        { name: "Best Sellers", slug: "best_sellers" },
        { name: "Chocolate cakes", slug: "chocholate_cakes" },
        { name: "Fruit cakes", slug: "fruit_cakes" },
        { name: "Coffee cakes", slug: "coffee_cakes" },
        { name: "Breakfast bars", slug: "breakfast_bars" },
        { name: "Energy bites", slug: "energy_bites" },
        { name: "Chocolate bars", slug: "chocholate_bars" },
      ],
    },
  ],
};
